import React from 'react';

const Terms = () => {
  return (
    <div style={{
      backgroundColor: '#0D1117',
      color: '#E6EDF3',
      fontFamily: '"DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      minHeight: '100vh',
      padding: '40px 20px',
      boxSizing: 'border-box'
    }}>
      <div style={{
        maxWidth: '700px',
        margin: '0 auto'
      }}>
        {/* Back to Home Link */}
        <div style={{ marginBottom: '32px' }}>
          <a
            href="/"
            onClick={(e) => {
              e.preventDefault();
              window.location.href = '/';
            }}
            style={{
              color: '#F0A500',
              textDecoration: 'none',
              fontSize: '14px',
              fontWeight: '500',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '4px',
              transition: 'opacity 0.2s'
            }}
            onMouseEnter={(e) => e.currentTarget.style.opacity = '0.8'}
            onMouseLeave={(e) => e.currentTarget.style.opacity = '1'}
          >
            ← Back to home
          </a>
        </div>

        {/* Title & Subtitle */}
        <h1 style={{
          fontFamily: '"Instrument Serif", Georgia, serif',
          fontSize: '32px',
          fontWeight: 'normal',
          color: '#F0A500',
          margin: '0 0 8px 0'
        }}>
          Terms of Service
        </h1>
        <p style={{
          fontSize: '13px',
          color: '#8B949E',
          margin: '0 0 40px 0'
        }}>
          Last updated: June 2026
        </p>

        {/* Sections */}
        {[
          {
            title: "1. Acceptance of terms",
            content: "By using MailPulse, you agree to these terms. If you do not agree, please do not use the service."
          },
          {
            title: "2. Description of service",
            content: "MailPulse is an AI-powered email assistant that connects to your Gmail account to analyze, prioritize, and summarize emails, and generate suggested replies and voice briefings."
          },
          {
            title: "3. Your responsibilities",
            content: "You are responsible for maintaining the security of your Google account. MailPulse only requests read-only access and will never ask for your password."
          },
          {
            title: "4. AI-generated content",
            content: "Summaries, priority labels, and draft replies are generated by AI and may contain errors. Always review AI-generated content before taking action, especially draft replies, before sending."
          },
          {
            title: "5. Service availability",
            content: "MailPulse is provided \"as is\" during beta. We do not guarantee uninterrupted availability and may modify or discontinue features at any time."
          },
          {
            title: "6. Limitation of liability",
            content: "MailPulse is not liable for any damages arising from use of the service, including but not limited to missed emails, incorrect AI summaries, or data loss."
          },
          {
            title: "7. Changes to terms",
            content: "We may update these terms periodically. Continued use of the service constitutes acceptance of updated terms."
          },
          {
            title: "8. Contact",
            content: (
              <>
                Questions about these terms:{' '}
                <a href="mailto:yeshwanth9750@gmail.com" style={{ color: '#F0A500', textDecoration: 'none' }}>
                  yeshwanth9750@gmail.com
                </a>
              </>
            )
          }
        ].map((section, idx) => (
          <div key={idx} style={{ marginBottom: '24px' }}>
            <h2 style={{
              fontSize: '18px',
              fontWeight: '600',
              color: '#E6EDF3',
              margin: '0 0 10px 0'
            }}>
              {section.title}
            </h2>
            <div style={{
              fontSize: '14px',
              lineHeight: '1.7',
              color: '#8B949E'
            }}>
              {section.content}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Terms;
